trigger:
- main

variables:
  dockeRepository: dheerajlearningdocker/gradle-app
  containerRegistry: dockerRepo
  kube-serviceConnection: k3d-dev


pool: linux-agent


stages:
- stage: SonarAnalysis
  jobs:
  - job: SonarAnalysis
    container: openjdk:11
    steps:
    - task: SonarQubePrepare@5
      inputs:
        SonarQube: 'sonar'
        scannerMode: 'Other'
    - task: Gradle@3
      inputs:
        gradleWrapperFile: 'gradlew'
        workingDirectory: './'
        tasks: 'sonarqube'
        publishJUnitResults: false
        sonarQubeRunAnalysis: false
        spotBugsAnalysis: false
      
    

# - task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'