trigger:
- main

pool: linux-agent


stages:
- stage:
  jobs:
  - job: SonarAnalysis
    container: openjdk:11
    steps:
    - task: SonarQubePrepare@5
      inputs:
        SonarQube: 'sonar'
        scannerMode: 'Other'
    - task: Gradle@3
      inputs:
        gradleWrapperFile: 'gradlew'
        workingDirectory: './'
        tasks: 'sonarqube'
        publishJUnitResults: false
        sonarQubeRunAnalysis: false
        spotBugsAnalysis: false