replicaCount: 1

image:
  repository: dheerajlearningdocker/gradle-app
  tag: 1
  ImagePullPolicy: IfNotPresent

containerPort: 8080

service:
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 30080
